name: "Aggregate GitHub issues for ADR"
description: "Search ADR issues by given labels and list them with status on one issue named as given title"
author: "44smkn"
inputs:
  summary-issue-title:
    description: "Title of github issue that aggregates ADR issues"
    required: true
  adr-issue-labels:
    description: "Narrow down the target of aggregation by AND conditions using the specified label"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
